ztimer/timerscheduler.go
ztimer/timerscheduler_test.go

附上测试代码：
```
var Scheduler *ztimer.TimerScheduler
func init() {
Scheduler = ztimer.NewAutoExecTimerScheduler()
}
```
```
f1 := ztimer.NewDelayFunc(func(v ...interface{}) {
log.Println("aaaaaa")
}, []interface{}{})
f2 := ztimer.NewDelayFunc(func(v ...interface{}) {
log.Println("bbbbbb")
}, []interface{}{})
timerId1,_:=Scheduler.CreateTimerAfter(f1, time.Duration(3)*time.Second)
timerId2,_:=Scheduler.CreateTimerAfter(f2, time.Duration(5)*time.Second)
log.Printf("timerId=%d ,timerId2=%d\n",timerId1,timerId2)
Scheduler.CancelTimer(timerId1)    //删除timerId1
```
预期结果：5秒后打印bbbbbb
实际结果：3秒后打印aaaaaa，5秒后打印bbbbbb
该问题已修复

修复时间轮无法通过CancelTimer方法删除Timer的bug

---

zlog/zlogger.go

ZinxLogger结构体里有buf，后续调用formatHeader可以不用传参的形式。

修改zlogger的formatHeader

---

znet/connmanager.go
znet/server.go

socket listen bug

---

examples/zinx_client/main.go
znet/connection.go

解决在连接close回调中发送消息死锁问题，但是不建议这里发送消息，因为发送消息是异步的，多半是收不到的

fix issue #117

---

zinx_app_demo/mmo_game/server.go
znet/connection.go

测试时，远程服务器网络带宽打满时，缓冲队列没有超时机制，卡死挂起，导致主程序挂起。带宽恢复后，server 也不能提供连接服务。 增加超时机制后，即时遇到超时和带宽打满情况，也可正常运行。

fix: msgBuffChan加上超时判断，在网络阻塞和超时情况下不会阻塞服务。网络恢复后，服务继续运行

---

znet/connection.go
znet/server_test.go

修复sendMsg与Close并发运行时可能出现的死锁bug #134 
采用直接write写的方式，用channel后并并能使sendMessage方法能同步运行，而且多了一个channel开销，并因此引出bug，所以就干脆将这个channel删了，直接使用write发送。
这样改还有一个好处，就是能正常返回write的错误信息，避免成功调用此方法，但信息由于对方关闭连接等原因没有实际发送的尴尬bug(之前虽然打日志了，但代码中无法感知，也就没法做异常判断流程)

修复sendMsg与Close并发运行时可能出现的死锁bug

---

znet/connection.go

- 描述：
- CallOnConnStart 函数后于 `go c.StartReader() `go c.StartWriter()` 执行，会导致本该在连接初始化执行的逻辑后于请求执行（reader goroutine，writer goroutine），导致逻辑顺序错乱 
- 产生场景：
- 服务器压测
- 触发环境：
- 多核并发情况下，runtime.GOMAXPROCS > 1

更改CallOnConnStart函数执行位置

---

examples/Zinx_NewRouter/Client.go
examples/Zinx_NewRouter/Server.go
examples/Zinx_NewRouter/conf/zinx.json
utils/UserConf.go
ziface/imsghandler.go
ziface/irouter.go
ziface/iserver.go
znet/msghandler.go
znet/router.go
znet/server.go

原本的路由 prehandle handle PostHandle 三者只是依顺序执行无关联且每个路由都需要用户自己构建路由结构体，这个pr修改成路由为传入指定函数的形式 用Next Abort 来操作顺序，用户也不再需要每一个路由都创建结构体实例，只需要传入指定类型的函数即可，示例如examples/Zinx_NewRouter
新增了一个配置类和新的Server构建方法，用于用户配置注入到配置类来定制参数

修改了原本的路由方式，新加入用户自定义配置类

---

examples/zinx_NewRouter/Client.go
examples/zinx_NewRouter/Server.go
examples/zinx_NewRouter/conf/zinx.json
utils/UserConf.go
ziface/irequest.go
znet/connection.go
znet/msghandler.go
znet/request.go
znet/server.go

新增一个用户配置类和用户配置构造Server的方法，用户可以通过注入配置的方式通过配置类来实现自定义配置
之前包涵在新路由的PR中，被恢复了
优化原本的路由函数 通过增加 irequest 中的接口方法和修改MsgHandle中的调用方法 在不影响原本方式情况下 提供 之前 PR #162      的Next和Abort 方法

新增用户配置类，优化原本的路由方式

---

Znotify/ConnAndId.go
Znotify/Notify.go
Znotify/Notify_test.go
Znotify/conf/zinx.json
ziface/Inotify.go
znet/connection.go

1.调整 msgBuffChan的初始化，如果没有调用过SendBuffMsg则不初始化，且也不启动StartWrite方法，因为此方法目前只会读取msgBuffChan中的值 。并且 在finalizer()方法执行中再判断一下 msgBuffChan是否开启，开启才关闭这个管道否则会panic
2. 添加了一个id和Conn的映射和Notify接口和操作，用以提供 #169  Issues的提案的实现，通过id映射由框架来发送通知 来实现如 ：玩家对玩家的聊天，单独对某个玩家的通知或者是全体通知类的操作

调整 msgBuffChan的初始化 和StartWrite方法启动时机 添加Notify层和i连接映射

---

README-CN.md
README.md
examples/zinx_interceptor/interceptors/interceptor_1.go
znet/heartbeat.go
znotify/notify.go

1. 修复一些文本和引用错误
2. notify 全量推送时，单个链接错误不应该直接return,应该继续执行其他的conn

fix(typos): 修复一些文本错误

---

zinterceptor/builder.go
zinterceptor/framedocder.go
znet/connection.go
znet/heartbeat.go
znet/server.go

1，修正大量玩家（比如100名）同时发起请求时的数据竞争问题。
原因：所有消息处理中使用的Builder都是同一对象，而ic.req在责任链调用req.SetData时会发生错乱
2，修正getUnadjustedFrameLength中客户端发送恶意数据时，返回负数并引发panic的问题。
原因：4字节的最大值是MaxUint32而非MaxInt32
3，修正reader.Peek造成第一条消息丢失的问题。
原因：执行reader.Peek后，conn的数据已经被扇出，后续应该使用reader而非conn。
4，修正用户自定义beatfunc无效的问题
原因： (h *HeartbeatChecker) Clone()中，beatfunc未被克隆

修正了一些网络连接相关的问题

---

znet/connection.go
znet/responsewriter.go
znet/server.go

1，修正example/client由于没有reader无法正常运行的问题；
2，修正wsConn中用户自定义beatfunc无效的问题；
3，修正用户非法访问（比如在浏览器地址栏直接输入服务器host）时，引发panic的问题；
4，修正reader.Peek在用户非法访问（比如建立tcp连接后不发送任何消息）时，会导致新client无法被Accept的问题。

Fixed issues that would cause the server to stop

---

znet/request.go
znet/server.go

1，整合四种newServer方法，并将打印顺序统一成先打印Logo再打印Config
2，新版本路由BindRouterSlices的行为和旧版路由BindRouter对齐，仅绑定路由不重置索引

Simplify code

---

zutils/shard_lock_map.go
zutils/shard_lock_map_bench_test.go
zutils/shard_lock_map_test.go

Provide a more efficient map that minimizes lock granularity and lock holding time.

Shard lock Map: More efficient concurrent map

---

znotify/notify.go

1.replace common map with a shard lock map.
2.delete both 'notifyAll2' and 'notifyall' private function.

notify opt

---

znet/connection.go

在io频繁的场景中, 从客户端读取数据时, 减少内存申请次数, 提高效率.

update:Reduce buffer allocation times to improve efficiency

---

go.mod
znet/connection.go

1.去掉写消息读写锁
2.用CAS保护关闭时，finalizer线程安全
3.修复原来Go StartWriter时存在的多线程竞争问题（可能导致开启多个写协程）

connection模块修复与优化

---

znet/connection.go

为了不使用锁，此处去掉主动关闭close(c.msgBuffChan) 让系统自动GC 该channel。可避免写数据时出现竞争：往关闭的channel写数据的panic错误

解决connection模块写时，出现往空的channel写的panic错误

---

zlog/logger_core.go

Refactor verifyLogIsolation() for a more concise expression

---

znet/connmanager.go
znet/heartbeat.go
znet/kcp_connection.go
znet/msghandler.go

去除这些日志，改成debug，否则启动后一大堆日志刷屏，导致真正的日志看不到

去除不必要的info日志

---

znet/connection.go

fix Bug  https://github.com/aceld/zinx/issues/315  [Panic]: send on closed channel

fix bug: [Panic]: send on closed channel

---

examples/zinx_kcp/server.go
zconf/globalobj.go
zconf/userconf.go
znet/server.go

虽然kcp对丢包超时等情况做了大量优化，
但是在一些实时较高的场景（比如游戏）还是难以接受。此时fec就可以和kcp一起使用，利用fec的纠错机制进一步减少重传
相关阅读:
https://vearne.cc/archives/39331
https://github.com/xtaci/kcp-go/blob/master/fec_test.go
https://github.com/wangyu-/UDPspeeder/blob/branch_libev/doc/README.zh-cn.md
https://segmentfault.com/a/1190000041690310

增加kcp-go的 fec配置

---

ziface/imsghandler.go
znet/msghandler.go
znet/server.go

* 把`decoder` 移动到`Interceptors`最前面，方便后面添加一些中间件可以获取当前msg的一些基本信息

fix(decoder): move decoder to interceptor head

---

znet/connection.go

connection isClose 方法判断,防止 c.ctx 不存在导致程序 panic

connection isClose 方法判断,防止 c.ctx 不存在导致程序 panic

---

znet/ws_connection.go

用读锁，无法避免并发写入消息，都能走入写消息的逻辑里面，导致并发写入错误

fix: read lock -> write lock

---

examples/zinx_dynamic_bind/client/client.go
examples/zinx_dynamic_bind/server/conf/zinx.json
examples/zinx_dynamic_bind/server/server.go
zconf/zconf.go
znet/msghandler.go

具体实现: DynamicBind 模式 也是一个连接对应一个worker, 给新连接分配worker时, 优先从已初始化好的工作池里取，如果工作池里的worker已经用完了，没有空闲的worker，就动态创建一个worker绑定到每个连接。这个临时创建的worker, 会在连接断开后销毁。

Feature/dynamic bind: 增加DynamicBind工作池模式,类似于Bind工作池模式，每个连接绑定一个worker, 但不像Bind模式那样会闲置很多worker

---

ziface/iclient.go
znet/client.go
znet/options.go
znet/server.go
znet/ws_connection.go

使用http request context传递一些鉴权后设置的信息
客户端支持连接指定地址及参数
实现客户端连接服务端的第一个请求开始验证token,验证成功后，可以设置一些可信任的参数到上下文中，后续连接触发SetOnConnect方法中可以从上下文中读取并设置到属性中，后续连接都可以读取使用。

feat: 扩展websocket鉴权与wsConn的关联

---

zutils/witer.go

您好最近我正在学习您的框架，仔细阅读了zutils/writer.go中的代码，发现了一下几个可能可以被优化的地方：
- 当1s内通过`Writer`写入大量数据的时候可能造成多次`rotate`，即造成多次按照大小切割。而其中`os.Create`创建压缩日志文件的方法会覆盖已经存在的文件，从而丢失写入的日志。我做了如下实验：将`sizeMiB`改为1KB，然后如右图模拟短时间内大量日志写入。会出现明显的日志丢失问题。所以我考虑是否能将压缩日志的后缀增加到微秒级别，从而尽量避免覆盖，具体实现如下面第二张图。
- 在按照大小切割的时候是否需要考虑`w.bw`缓冲区中未写入文件的数据大小，修改如下图：
- `appendInt`函数是否可以被删除，因为下面这部分代码的实现逻辑和`t.AppendFormat(nil, time.RFC33391)`的逻辑相同，而且`w.creates`生成的时候也是调用的`AppendFormat`方法。

Writer 修改：压缩时后缀变为微秒级别 + 按大小切割时考虑缓冲区中未写入的数据 + appendInt 疑似为重复代码

---

.github/workflows/reviewdog.yml

https://github.com/aceld/zinx/security/code-scanning/2

Fix CodeQL: Actions Job or Workflow does not set permissions

---

znet/connection.go

fix: https://github.com/aceld/zinx/issues/357

feat: 优化缓冲发送逻辑，减少缓冲发送小数据包的频繁系统调用

---

zinterceptor/framedecoder.go

fix: https://github.com/aceld/zinx/issues/352

delete FrameDecoder lock, delete Decode() lock
